# Generated by Django 4.0.4 on 2022-05-14 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
