# Generated by Django 4.0.4 on 2022-05-23 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_operation_timestamp_operation_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('title', 'date', 'amount', 'category', 'user')},
        ),
    ]
